/**
 * Level 6–7 items: "exam-style" and "advanced transfer".
 *
 * These are deliberately harder than the official samples. The official material says its samples
 * are "only a selection" and do not necessarily reflect the difficulty of the real test, so the
 * mastery ladder needs items above the sample tier — items that combine two relations, that
 * describe a situation instead of stating a formula, or that require a model judgement rather
 * than a computation.
 */

import { Q } from './helpers';
import type { Question } from '../types';
import type { AuthoredOption, AuthoredSpec } from './helpers';

const o = (text: string, errorTag: AuthoredOption['errorTag'], why: string): AuthoredOption => ({ text, errorTag, why });

export const ADVANCED: AuthoredSpec[] = [
  {
    id: 'adv-vec-01',
    domainId: 'D02',
    conceptIds: ['C02.area', 'C02.cross', 'C02.angle'],
    label: 'OFFICIAL_SAMPLE',
    stem:
      'Two vectors in the plane are given as $\\vec{a} = (4, 0)$ and $\\vec{b} = (2, 2)$. A student claims: "the area of the parallelogram they span is 8, and the angle between them is 45°." Which assessment is correct?',
    options: [
      o('Both claims are correct.', 'none', 'Correct: $|\\vec{a}\\times\\vec{b}| = |4\\cdot2 - 0\\cdot2| = 8$, and $\\cos\\varphi = \\frac{8}{4\\sqrt{8}} = \\frac{1}{\\sqrt2}$, so $\\varphi = 45°$.'),
      o('The area is correct, the angle is larger than 45°.', 'calculation_slip', 'The cosine is $\\frac{1}{\\sqrt2} \\approx 0{,}707$, which is exactly 45°, not a larger angle.'),
      o('The area is 16 and the angle is 45°.', 'concept_confusion', '16 is the area of the rectangle spanned, not of the parallelogram: the parallelogram area is the magnitude of the vector product.'),
      o('The area is 8 and the angle is 90°, because the vectors are not parallel.', 'rule_misapplication', 'Not being parallel only excludes 0° and 180°; the actual angle comes from the cosine, which is not zero here.'),
    ],
    correct: 0,
    difficulty: 6,
    reasoningType: 'multi_step_application',
    cognitiveMove: 'explain_or_critique',
    style: 'statement_compare',
    hints: ['Compute the vector product first, then the cosine of the angle.', 'Both quantities can be expressed with the same two products.'],
    explanation: {
      testing: 'Combining the vector product (area) with the scalar product (angle) and judging a compound claim.',
      matters: 'The components of both vectors, and the fact that the area and the angle come from different products.',
      irrelevant: 'The position of the vectors in the plane: only their components matter, not where they are drawn.',
      concept: '$|\\vec{a}\\times\\vec{b}|$ is the spanned area; $\\cos\\varphi = \\frac{\\vec{a}\\cdot\\vec{b}}{|\\vec{a}||\\vec{b}|}$ gives the angle.',
      why: 'Both quantities are determined by the same two products, so a compound claim must be checked twice — a correct area says nothing about the angle.',
      steps: [
        '$\\vec{a}\\times\\vec{b} = 4\\cdot2 - 0\\cdot2 = 8$ in the plane, so the area is $|8| = 8$.',
        '$\\vec{a}\\cdot\\vec{b} = 4\\cdot2 + 0\\cdot2 = 8$; $|\\vec{a}| = 4$, $|\\vec{b}| = \\sqrt{8} = 2\\sqrt2$.',
        '$\\cos\\varphi = \\frac{8}{4\\cdot2\\sqrt2} = \\frac{1}{\\sqrt2} \\Rightarrow \\varphi = 45°$.',
        'Both parts of the claim hold.',
      ],
      distractorWhy: [
        'Correct — the reasoning in the option matches the computation.',
        'The cosine value was misread; $1/\\sqrt2$ is 45°, not larger.',
        'Confusing the rectangle area (16) with the parallelogram area (8).',
        'Non-parallel does not mean perpendicular; the perpendicular case requires a zero scalar product, which is not the case here.',
      ],
      trap: 'Checking only the first part of a compound claim, or believing that a non-zero angle is automatically 90°.',
      transfer: 'Every "is this statement correct?" item should be split into its parts and each part verified separately — the exam uses compound claims precisely because they punish partial checking.',
    },
    tags: ['advanced'],
  },
  {
    id: 'adv-hyd-01',
    domainId: 'D06',
    conceptIds: ['C06.buoy', 'C06.displaced', 'C06.stability'],
    label: 'OFFICIAL_SAMPLE',
    stem:
      'Two identical cargo boxes of 12 t each float in the same water. Box A is narrow and tall, box B is wide and flat. Which statement about floating and stability is correct?',
    options: [
      o('Both boxes displace the same mass of water, but B resists tilting more strongly.', 'none', 'Correct: the displaced mass equals the body mass in both cases (12 t), and the wider hull moves its displaced water sideways faster when it tilts.'),
      o('B displaces more water because it has a larger surface area in contact with the water.', 'concept_confusion', 'Contact area does not enter the floating condition; only the displaced *mass* matters, and it is fixed by the weight.'),
      o('A is more stable because its centre of gravity is higher, giving the water more leverage.', 'causal_direction_reversed', 'A higher centre of gravity makes a body *less* stable: the restoring effect depends on how far the displaced water moves sideways, not on height.'),
      o('Both displace the same mass, and both resist tilting equally because the mass is identical.', 'wrong_assumption', 'Equal mass means equal displaced mass, but stability depends on the hull shape — the same weight in a wider hull is more stable.'),
    ],
    correct: 0,
    difficulty: 6,
    reasoningType: 'conceptual_discrimination',
    cognitiveMove: 'classify_situation',
    style: 'statement_compare',
    hints: ['Start with the floating condition: what must equal the body weight?', 'Then ask which geometric quantity decides the restoring effect.'],
    explanation: {
      testing: 'Separating the floating condition (mass) from the stability condition (geometry).',
      matters: 'The equal masses (12 t each) and the different hull widths.',
      irrelevant: 'The absolute size of the boxes: only the shape difference matters for the comparison.',
      concept: 'Floating: displaced mass = body mass. Stability: the restoring moment grows with a wider hull.',
      why: 'Buoyancy is an equilibrium statement about weight; stability is a statement about geometry. A single body can satisfy the first and still be tender in the second.',
      steps: [
        'Floating condition: each box displaces 12 t of water, regardless of shape.',
        'A tilting hull moves its displaced water sideways; the wider the beam, the further it moves.',
        'A larger sideways shift produces a larger restoring moment, so B is the more stable of the two.',
        'Both statements are therefore correct together.',
      ],
      distractorWhy: [
        'Correct — the reasoning in the option matches the computation.',
        'Contact area is irrelevant to buoyancy; the displaced mass is fixed by the weight.',
        'A higher centre of gravity reduces stability — the reason is reversed.',
        'Stability is a geometric property, not a consequence of equal mass.',
      ],
      trap: 'Assuming equal weight implies equal behaviour in the water — which is true for floating, false for stability.',
      transfer: 'The same distinction decides why a wide ferry is comfortable and a narrow canoe is not, at equal displacement.',
    },
    tags: ['advanced'],
  },
  {
    id: 'adv-eoq-01',
    domainId: 'D09',
    conceptIds: ['C09.qstar', 'C09.scaling', 'C09.value'],
    label: 'OFFICIAL_SAMPLE',
    stem:
      'A supplier offers a 2 % discount on the **purchase price** if orders are placed in larger quantities. The order-quantity model as taught in the official material',
    options: [
      o('does not contain the purchase price, so the discount cannot change $Q^{*}$ inside the model — the decision must be taken by comparing total costs with and without the discount.', 'none', 'Correct: the model minimises ordering and holding costs only; a price break is a comparison of two regimes, not an input to the formula.'),
      o('should be re-run with the discounted price in the holding cost and the square root recomputed.', 'model_assumption_error', 'The discount applies to the purchase price per unit, not automatically to the holding cost rate, and substituting it into the formula does not answer whether the larger order is worth it.'),
      o('shows that larger orders always reduce total cost, so the discount should be taken.', 'overprecision', 'Larger orders reduce *ordering* cost but increase holding cost; total cost rises again beyond $Q^{*}$.'),
      o('requires replacing $Q^{*}$ by the discount quantity because the demand is constant.', 'wrong_assumption', 'Constant demand does not make the discounted quantity optimal; the two candidate quantities must be compared on total cost.'),
    ],
    correct: 0,
    difficulty: 7,
    reasoningType: 'optimisation_reasoning',
    cognitiveMove: 'general_case',
    style: 'statement_compare',
    hints: ['What costs does $Q^{*} = \\sqrt{2DS/H}$ actually balance?', 'Where would a discount on the unit price appear in a total-cost statement?'],
    explanation: {
      testing: 'Recognising the boundary of a model — what it optimises and what it cannot decide.',
      matters: 'The model contains ordering cost and holding cost; the purchase price is not in it.',
      irrelevant: 'The size of the discount (2 %): the principle holds for any discount, the arithmetic decides the case.',
      concept: 'The model minimises ordering plus holding cost. A price break creates two regimes whose total costs (including purchase cost) must be compared.',
      why: 'A formula cannot optimise a quantity it does not contain. The correct procedure is to evaluate the total annual cost at the unconstrained optimum and at the smallest quantity that earns the discount, and compare.',
      steps: [
        'Total annual cost = purchase cost + ordering cost + holding cost.',
        'Inside the model, purchase cost is constant, which is why it does not appear in $Q^{*}$.',
        'With a price break, purchase cost depends on the quantity, so the model no longer covers the decision.',
        'Compare the two candidate quantities on the full total cost and choose the cheaper one.',
      ],
      distractorWhy: [
        'Correct — the reasoning in the option matches the computation.',
        'The holding-cost rate is a storage cost, not the purchase price; substituting it in changes the wrong quantity.',
        'Total cost has a minimum; ordering more always increases the holding term.',
        'Constant demand is an assumption of the model, not an argument for the discounted quantity.',
      ],
      trap: 'Treating the square-root formula as a general answer for every procurement question.',
      transfer: 'Any optimisation model inherits the boundaries of its cost statement; decisions outside that statement need a direct comparison of alternatives.',
    },
    tags: ['advanced', 'multi-concept'],
  },
  {
    id: 'adv-res-01',
    domainId: 'D11',
    conceptIds: ['C11.mixed', 'C11.general', 'C11.document'],
    label: 'OFFICIAL_SAMPLE',
    stem:
      'A study reports: "In our survey of 1 200 employees, satisfaction was higher after the new roster was introduced. We also interviewed 24 employees, who explained why the roster helped them plan their week better. During the survey we added two items about shift length, so we report the results for those items separately for the two halves of the sample." Which methodological assessment is most defensible?',
    options: [
      o('The design combines a quantitative trend with a qualitative mechanism, and the added items are handled as the material requires — documented, with the comparability consequence reported.', 'none', 'Correct: the mixed design answers both the "whether" and the "why" question, and the change to the instrument is documented and its consequence reported rather than ignored.'),
      o('The study is invalid because a questionnaire may not be changed once data collection has begun.', 'overprecision', 'The material allows modifications; it warns that they can reduce significance or comparability, which is exactly why the split reporting matters.'),
      o('The interviews cannot support the mechanism claim because 24 employees are too few to be generalisable.', 'scope_error', 'Mechanism claims from interviews are not frequency claims; their role is explanatory, and the reader judges transferability rather than statistical generalisation.'),
      o('The survey alone answers the question, so the interviews are unnecessary additional work.', 'irrelevant_data_used', 'The survey shows that satisfaction rose; it does not show *why*, which is the second half of the research question.'),
    ],
    correct: 0,
    difficulty: 7,
    reasoningType: 'evidence_evaluation',
    cognitiveMove: 'general_case',
    style: 'critique_reasoning',
    hints: ['Separate the "whether" question from the "why" question before judging the design.', 'Ask what the material says about changing an instrument mid-project.'],
    explanation: {
      testing: 'Judging a complete mixed-method design, including the treatment of an instrument change.',
      matters: 'Two questions (trend and mechanism), two strands (survey and interviews), and the documented change with its reported consequence.',
      concept: 'Mixed designs answer complementary questions; documented changes are permissible, hidden ones are not.',
      why: 'Each element of the design maps onto a part of the research question, and the methodological requirement for a change is documentation plus disclosure of the consequence — both present here.',
      steps: [
        'Split the question: does satisfaction differ (quantitative) and why (qualitative).',
        'Match the strands: survey with trend, interviews with mechanism.',
        'Assess the instrument change: documented and its comparability consequence reported for the two halves.',
        'Conclude that all parts are defensible as described.',
      ],
      distractorWhy: [
        'Correct — the reasoning in the option matches the computation.',
        'Modifications are not forbidden; the material states they may reduce significance or comparability, which is why they must be reported.',
        'Interview findings are transferred, not generalised statistically; the sample size objection applies the wrong standard.',
        'The survey cannot establish a mechanism, so the interviews answer a question the survey does not.',
      ],
      trap: 'Applying the "no changes" instinct instead of the documented-change rule, or dismissing one strand of a mixed design as redundant.',
      transfer: 'Evaluation reports, clinical protocols and policy evaluations are all judged by the same rule: what each evidence strand can show, and whether changes were disclosed.',
    },
    tags: ['advanced', 'multi-concept'],
  },
  {
    id: 'adv-sci-01',
    domainId: 'D13',
    conceptIds: ['C13.model', 'C13.scaling', 'C05.gas'],
    label: 'PREPARATION_EXTENSION',
    stem:
      'A balloon rises from the ground to 5 000 m. The pressure falls by about 40 % and the temperature falls as well. Which prediction about the volume is most defensible?',
    options: [
      o('The volume grows substantially — by more than the pressure ratio would suggest is impossible, and the cooling works against it, so the pressure effect dominates but not by the full 1/0,6 factor.', 'none', 'Correct: the falling pressure expands the gas, while the falling temperature contracts it; the pressure effect is the larger one, so the volume grows but not by the full factor $1/0{,}6$.'),
      o('The volume grows by exactly the factor $1/0{,}6 \\approx 1{,}67$ because pressure and volume are inversely proportional.', 'model_assumption_error', 'The inverse relation $pV = $ constant holds at *constant temperature*; the ascent also cools the gas, so the factor is an upper bound, not the answer.'),
      o('The volume is unchanged because the temperature also falls, and the two effects cancel.', 'wrong_assumption', 'There is no reason for the two effects to cancel exactly: their magnitudes are set by different physical relations.'),
      o('The volume cannot be predicted without knowing the amount of gas in the balloon.', 'concept_confusion', 'The amount of gas is fixed inside a closed balloon; it cancels out of the ratio, so the prediction does not need it.'),
    ],
    correct: 0,
    difficulty: 7,
    reasoningType: 'estimation_scaling',
    cognitiveMove: 'effect_of_change',
    style: 'effect_direction',
    hints: ['Which relation would hold if the temperature were constant?', 'Now ask what the falling temperature does to the same gas.'],
    explanation: {
      testing: 'Applying a model only within the conditions that make it valid — and reasoning about two opposing effects.',
      matters: 'The pressure ratio (about 1,67), the cooling, and the fact that the balloon is closed (the amount of gas is constant).',
      concept: 'Boyle\u2019s law is the isothermal case of the ideal-gas relation; temperature appears only in the general form.',
      why: 'The general relation $pV = nRT$ contains both effects. A 40 % pressure drop alone would give a factor 1,67; cooling reduces the volume and therefore lowers that factor without reversing it.',
      steps: [
        'Fixed amount of gas: $V \\propto T/p$.',
        'Pressure falls to about 0,6 of the ground value, which alone would multiply the volume by about 1,67.',
        'Temperature also falls, which multiplies the volume by a factor below 1.',
        'Net effect: a substantial volume increase, but smaller than 1,67 — and the balloon bursts or the skin stretches, depending on how the material behaves.',
      ],
      distractorWhy: [
        'Correct — the reasoning in the option matches the computation.',
        'This is the isothermal result; the ascent is not isothermal.',
        'Nothing forces the two effects to cancel exactly.',
        'The amount of gas is fixed, so it cancels in the ratio.',
      ],
      trap: 'Using $p_1V_1 = p_2V_2$ whenever a gas is involved, without checking whether the temperature is constant.',
      transfer: 'Every model has a "held constant" clause. Items that change two variables at once test whether you notice it — and in engineering practice the same oversight breaks a calculation.',
    },
    tags: ['advanced', 'extension'],
  },
  {
    id: 'adv-data-01',
    domainId: 'D03',
    conceptIds: ['C03.distort', 'C03.gradient', 'C01.ratio'],
    label: 'OFFICIAL_FIELD_LIST',
    stem:
      'A chart shows a company’s revenue from 100 to 104 (in millions) with a vertical axis from 99 to 105, and reports "strong growth". A second chart shows the same company’s cost from 80 to 84 with an axis from 0 to 100 and reports "stable cost". Which statement is correct?',
    options: [
      o('Both descriptions are misleading in the same way: the trimmed axis exaggerates the revenue change, while the full axis hides a cost change of the same relative size.', 'none', 'Correct: revenue rose 4 % and cost rose 5 % — the *relative* changes are comparable, and only the axes make one look dramatic and the other flat.'),
      o('The descriptions are fine because each chart uses its own scale.', 'graph_misread', 'Each chart may be internally consistent, but comparing the stories they tell requires looking at the relative change, not the visual slope.'),
      o('The revenue description is misleading, the cost description is not, because the cost axis starts at zero.', 'overprecision', 'A full axis avoids exaggeration but does not make the *comparison* fair: a 5 % cost rise is being described as stable.'),
      o('Neither chart can be judged without knowing the profit.', 'irrelevant_data_used', 'The question is about the description of the changes shown; profit is a different quantity.'),
    ],
    correct: 0,
    difficulty: 6,
    reasoningType: 'representation_transfer',
    cognitiveMove: 'interpret_representation',
    style: 'graph_choice',
    hints: ['Compute the relative change of each quantity first.', 'Then ask what each axis choice does to the visual impression.'],
    explanation: {
      testing: 'Judging a presentation against the underlying relative changes rather than the visual impression.',
      matters: 'The two relative changes (4 % and 5 %) and the two axis ranges.',
      concept: 'A trimmed axis exaggerates differences; a full axis can hide them. The numbers decide, not the slope.',
      why: 'Both descriptions are produced by axis framing rather than by the data: the smaller relative change looks like a leap and the larger one looks like stability.',
      steps: [
        'Revenue: $\\frac{104-100}{100} = 4\\ \\%$. Cost: $\\frac{84-80}{80} = 5\\ \\%$.',
        'The trimmed axis (99–105) magnifies a 4 % change into a steep line.',
        'The full axis (0–100) compresses a 5 % change into a nearly flat line.',
        'Conclusion: the relative changes are comparable; the descriptions are the artefacts of framing.',
      ],
      distractorWhy: [
        'Correct — the reasoning in the option matches the computation.',
        'Internal consistency is not the issue; comparability is.',
        'The assessment is incomplete: an honest axis can still accompany a misleading description.',
        'Profit is irrelevant to the judgement about the two descriptions.',
      ],
      trap: 'Reading charts by slope instead of by relative change, and assuming an honest axis guarantees an honest statement.',
      transfer: 'The same check exposes misleading reporting in any dashboard, business case or policy brief.',
    },
    tags: ['advanced'],
  },
  {
    id: 'adv-arg-01',
    domainId: 'D15',
    conceptIds: ['C15.necessary', 'C15.quantifier', 'C15.inference'],
    label: 'PREPARATION_EXTENSION',
    stem:
      'A regulation states: "Every laboratory that handles category-3 material must keep a logbook and must have a safety officer." Which inference is valid?',
    options: [
      o('If a laboratory does not keep a logbook, it does not handle category-3 material.', 'none', 'Correct: the statement says category-3 handling is *sufficient* for keeping a logbook, so the absence of a logbook excludes that category (contraposition).'),
      o('Every laboratory with a safety officer handles category-3 material.', 'sufficient_necessary_confusion', 'The original statement gives no such reverse implication: having an officer is necessary for category-3 work, not evidence of it.'),
      o('A laboratory that handles other categories must also keep a logbook.', 'scope_error', 'The rule is limited to category-3 material; it says nothing about other categories.'),
      o('A laboratory can avoid the logbook by not appointing a safety officer.', 'inequality_direction', 'Both duties apply jointly to category-3 laboratories; dropping one does not remove the other.'),
    ],
    correct: 0,
    difficulty: 6,
    reasoningType: 'logical_deduction',
    cognitiveMove: 'general_case',
    style: 'reverse_question',
    hints: ['Write the rule as an implication: category-3 handling ⇒ logbook.', 'Which of the options is the contrapositive of that implication, and which one reverses it?'],
    explanation: {
      testing: 'Contraposition versus reversal of an implication in a rule (normative) text.',
      matters: 'The scope ("category-3 material") and the direction of the implication.',
      concept: 'From $A \\Rightarrow B$ one may infer $\\neg B \\Rightarrow \\neg A$ (contraposition), but not $B \\Rightarrow A$ (reversal).',
      why: 'Only the contrapositive is logically equivalent to the original rule; every other option either reverses the implication or widens its scope.',
      steps: [
        'Formalise: handling category-3 material ⇒ keeps logbook (and has a safety officer).',
        'Contrapositive: no logbook ⇒ does not handle category-3 material. That is option 1.',
        'Check the others: option 2 reverses the implication, option 3 widens the scope, option 4 treats the duties as alternatives.',
      ],
      distractorWhy: [
        'Correct — contraposition.',
        'Reversing the implication: a necessary condition is treated as if it were sufficient.',
        'The rule is limited to category-3 material; the inference says nothing about other categories.',
        'The two duties are stated jointly, not as alternatives.',
      ],
      trap: 'Reading "must" as evidence of the antecedent (the reverse direction), and reading a rule as if it covered everything.',
      transfer: 'Specifications, contracts and safety rules are all written as one-directional implications; reading them precisely is a professional skill in every field the module names.',
    },
    tags: ['advanced', 'extension'],
  },
  {
    id: 'adv-econ-01',
    domainId: 'D10',
    conceptIds: ['C10.breakeven', 'C10.marginal', 'C10.opportunity'],
    label: 'PREPARATION_EXTENSION',
    stem:
      'A workshop has fixed costs of €18 000 per month and a contribution margin of €30 per unit, so it breaks even at 600 units. It currently produces 600 units. A customer offers to buy 200 additional units at €18 each; the variable cost is €12 per unit, and the workshop has spare capacity. Which decision is correct, and why?',
    options: [
      o('Accept: the extra order contributes $(18-12)\\cdot200 = €1\\,200$ towards fixed costs, which is profit while spare capacity exists.', 'none', 'Correct: beyond break-even, the contribution of each extra unit is profit, and the spare capacity means no alternative use is displaced.'),
      o('Reject: the price of €18 is below the break-even price of €30 per unit.', 'definition_misuse', '€30 is the *contribution margin* needed to cover fixed costs at 600 units, not a minimum price for an additional unit that uses spare capacity.'),
      o('Reject: the average cost per unit at 600 units is €30, which is above €18.', 'ratio_error', 'Average cost includes the fixed costs that are already covered by the existing production; the decision at the margin compares only the price with the variable cost.'),
      o('Accept, but only because the fixed costs are sunk.', 'wrong_assumption', 'The fixed costs are not sunk — they are covered by the existing 600 units. The reason to accept is that the additional units contribute and displace nothing.'),
    ],
    correct: 0,
    difficulty: 7,
    reasoningType: 'optimisation_reasoning',
    cognitiveMove: 'classify_situation',
    style: 'critique_reasoning',
    hints: ['What does each *additional* unit add to the result?', 'Is anything else being given up by using the spare capacity?'],
    explanation: {
      testing: 'Marginal decision-making with spare capacity, using contribution rather than average cost.',
      matters: 'The variable cost (€12), the offered price (€18), the spare capacity, and the fact that existing production already covers the fixed costs.',
      irrelevant: 'The break-even quantity of 600 units: it is already reached, so it does not set a minimum price for additional units.',
      concept: 'Beyond break-even, each additional unit contributes (price − variable cost) to profit; average cost is not the decision criterion.',
      why: 'Only the incremental flows change: the order brings €3 600 of additional revenue and €2 400 of additional variable cost, so €1 200 of contribution. Fixed costs are unaffected because the existing production already covers them.',
      steps: [
        'Margin on the additional units: $18 - 12 = 6$ € per unit.',
        'Contribution of the order: $6 \\cdot 200 = 1\\,200$ €.',
        'No alternative use of the spare capacity is displaced, so the opportunity cost is zero.',
        'Fixed costs are unchanged, so the €1 200 improves the result — accept.',
      ],
      distractorWhy: [
        'Correct — the reasoning in the option matches the computation.',
        'The break-even price is not a price floor for spare capacity.',
        'Average cost is not a marginal cost; it contains fixed costs that do not change.',
        'The fixed costs here are covered, not sunk; the argument for accepting is the contribution, not the sunk cost.',
      ],
      trap: 'Rejecting profitable additional business because its price is below the average cost — the classic misapplication of average thinking to a marginal decision.',
      transfer: 'Airlines, hotels, printers and workshops all price spare capacity this way; the same reasoning also prevents the opposite error of justifying any order with "fixed costs are sunk".',
    },
    tags: ['advanced', 'extension'],
  },
  {
    id: 'adv-comp-01',
    domainId: 'D08',
    conceptIds: ['C08.growth', 'C08.trace', 'C13.scaling'],
    label: 'PREPARATION_EXTENSION',
    stem:
      'Two procedures find the largest value in a list of $n$ numbers. Procedure A compares every number with every other number. Procedure B sorts the list once and then reads the last value. For $n = 10$ procedure A takes about 45 comparisons and procedure B about 30 operations. Which statement is defensible for $n = 10\\,000$?',
    options: [
      o('B is far faster: A grows with $n^2$ while B grows more slowly, so the advantage increases with the size of the list.', 'none', 'Correct: the comparison counts belong to different growth classes, and the class difference dominates the constants at large $n$.'),
      o('A is faster, because with $n = 10$ it needed fewer operations.', 'linearity_assumption', 'The comparison at $n = 10$ compares constants, not growth: the ranking at small sizes does not carry over to 10 000.'),
      o('They are equivalent, because both must look at every number at least once.', 'concept_confusion', 'Both must indeed look at every number once, but A looks at every pair, which is the dominating term.'),
      o('Nothing can be said without knowing the exact operation costs.', 'overprecision', 'Exact constants are unknown, but the growth class difference of $n^2$ versus roughly $n\\log n$ is decisive at this size.'),
    ],
    correct: 0,
    difficulty: 6,
    reasoningType: 'estimation_scaling',
    cognitiveMove: 'general_case',
    style: 'critique_reasoning',
    hints: ['Classify each procedure by growth (constant, linear, quadratic, logarithmic).', 'Then ask which classification dominates when $n$ becomes large.'],
    explanation: {
      testing: 'Reasoning about growth classes rather than about measured times at a single small input size.',
      matters: 'The relation described for each procedure: all pairs versus one pass plus the sorting effort.',
      concept: 'Growth class dominates constants for large inputs.',
      why: 'A compares $\\frac{n(n-1)}{2}$ pairs — quadratic. B sorts and then reads: about $n\\log n$. At $n = 10\\,000$ the difference is of the order of 50 million versus 130 thousand operations.',
      steps: [
        'A: every pair, $\\frac{n(n-1)}{2} \\approx \\frac{n^2}{2}$ comparisons — quadratic.',
        'B: one sort, $\\approx n\\log_2 n$ — much slower-growing.',
        'At $n = 10$ the constants happen to make A look competitive; at $n = 10\\,000$: $\\approx 5\\cdot10^7$ versus $\\approx 1{,}3\\cdot10^5$.',
        'B is faster by a factor of a few hundred.',
      ],
      distractorWhy: [
        'Correct — the reasoning in the option matches the computation.',
        'A single small measurement cannot establish a growth ranking.',
        'Both touching every element does not make the procedures equivalent; the pair structure is what dominates.',
        'Exact constants are unnecessary when the classes differ by orders of magnitude.',
      ],
      trap: 'Extrapolating from a measurement at a small input size — the classic error that hides behind "benchmarks".',
      transfer: 'The same reasoning decides database designs, routing algorithms and even organisational processes: count the structure, then scale.',
    },
    tags: ['advanced', 'extension'],
  },
  {
    id: 'adv-mixed-01',
    domainId: 'D01',
    conceptIds: ['C01.ratio', 'C01.estimate', 'C03.distort', 'C13.precision'],
    label: 'OFFICIAL_FIELD_LIST',
    stem:
      'A report states: "Our model predicts €1 483 726 of savings, based on an estimated 12 000 users and an average saving of about €120 per user." Which criticism of the *presentation* of the result is strongest?',
    options: [
      o('The figure is overprecise: it is presented to the euro although the inputs are estimates, and $12\\,000 \\cdot 120$ already gives a round €1 440 000.', 'none', 'Correct: the precision of the output cannot exceed the precision of the inputs; "about €1,4 million" is the honest version of this calculation.'),
      o('The figure is wrong, because $12\\,000 \\times 120$ equals 1 440 000 and not 1 483 726.', 'calculation_slip', 'The two figures need not be equal: the €120 is an average, and the total depends on the actual distribution. The presentation is the problem, not the multiplication.'),
      o('The figure is too low, because savings usually grow faster than the user count.', 'wrong_assumption', 'There is nothing in the statement about growth of savings with users; that is speculation.'),
      o('Nothing is wrong: reporting the exact number shows that the model was computed carefully.', 'overprecision', 'Precision is not care. Presenting an estimate to the last euro suggests an accuracy the inputs cannot support.'),
    ],
    correct: 0,
    difficulty: 6,
    reasoningType: 'conceptual_discrimination',
    cognitiveMove: 'explain_or_critique',
    style: 'critique_reasoning',
    hints: ['Compare the precision of the inputs with the precision of the output.', 'What would the honest rounding of this estimate look like?'],
    explanation: {
      testing: 'Precision versus accuracy, applied to a reported quantity.',
      matters: 'The words "estimated" and "about" in the inputs, and the euro-level precision of the output.',
      irrelevant: 'Whether the model is good: the criticism is about how the result is presented.',
      concept: 'A computed value carries at most the precision of its inputs; extra digits suggest accuracy that does not exist.',
      why: 'With inputs of the order "about 12 000" and "about €120", the honest output is "about €1,4 million" — the last five digits are noise dressed as knowledge.',
      steps: [
        'The inputs are estimates: 12 000 users (about) and €120 each (about).',
        'Even the ideal product is 1 440 000 €, which differs from the reported figure in the leading digits.',
        'Precision of the output therefore has no support beyond roughly two significant figures.',
        'The strongest criticism is overprecision: report €1,4 million, or state a range.',
      ],
      distractorWhy: [
        'Correct — the reasoning in the option matches the computation.',
        'The exact product of the two rounded inputs is not the criterion; the averages and distributions make the difference legitimate.',
        'Growth of savings with users is not part of the statement — this is an invented assumption.',
        'Careful computation and honest reporting are different things.',
      ],
      trap: 'Reading extra digits as a sign of quality, and therefore accepting an overprecise forecast.',
      transfer: 'Charts, forecasts, dashboards and exam answers all lose credibility the same way: more digits than the data can carry.',
    },
    tags: ['advanced'],
  },
];

export const ADVANCED_AUTHORED: Question[] = ADVANCED.map((spec) => Q(spec));
